stopifnot(getWjIndex(j=2) == 2)
stopifnot(getCjABIndex(j=1, aInd=2, bInd=1, nAlts=3, nCats=1, nCrit=2) == 4)
stopifnot(getCjBAIndex(j=2, aInd=2, bInd=1, nAlts=3, nCats=1, nCrit=2) == 13)
stopifnot(getCjBhBh1Index(nCrit=2, nAlts=2, nCats=3, j=2, h=1) == 29)
stopifnot(getLambdaIndex(nAlts=1, nCrit=1, nCats=1) == 4)
